apiVersion: v1
kind: Pod
metadata:
  name: tools-backup-test-agent
  namespace: zcp-system
spec:
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: beta.kubernetes.io/arch
            operator: In
            values:
            - amd64
          - key: role
            operator: In
            values:
            - management
  containers:
  - args:
    - -c
    - tail -f /dev/null
    command:
    - /bin/sh
    image: alpine:3.7
    imagePullPolicy: IfNotPresent
    name: alpine 
    resources:
      requests:
        cpu: 100m
        memory: 128Mi
      limits:
        cpu: 100m
        memory: 128Mi
    volumeMounts:
    - mountPath: /root/.config/rclone
      name: rclone-config
    - mountPath: /etc/localtime
      name: timezone
  serviceAccountName: zcp-system-admin
  tolerations:
  - effect: NoSchedule
    key: management
    operator: Equal
    value: "true"
  - effect: NoExecute
    key: node.kubernetes.io/not-ready
    operator: Exists
    tolerationSeconds: 300
  - effect: NoExecute
    key: node.kubernetes.io/unreachable
    operator: Exists
    tolerationSeconds: 300
  volumes:
  - name: rclone-config
    configMap:
      name: tools-backup-rclone-config
  - name: timezone
    hostPath:
      path: /usr/share/zoneinfo/Asia/Seoul
      type: ""
